### ISSUE TITLE
Can't compile on 64bit

### ISSUE THREAD

**Issue by CyberKiller40** [fstltna/Imperium#1]
The Makefile for the clients has a hardcoded path to "/usr/lib/i386-linux-gnu/libpcre.a" this is a problem on 64bit platforms. During compilation I get:

make[1]: Entering directory `/home/ck/Gry/Imperium-master/Clients'
gcc  -DBROKEN_PIPE -DTERMIOS -DBROKEN_MKNOD -g -O2 -DFIFO_DIR="\"/usr/local/lib/imperium/fifo\"" -c -o ConImp.o ConImp.c
gcc -L/usr/lib/i386-linux-gnu -o ConImp ConImp.o ../Library/libimpm.a /usr/lib/i386-linux-gnu/libpcre.a -lc -lcrypt
gcc: error: /usr/lib/i386-linux-gnu/libpcre.a: No such file or directory

My system: openSUSE 13.1 amd64, installing a 32bit version of that lib didn't help (cause the path is wrong anyway)

BTW: you could add a link to here in the game text files, it took me a while to find this place (I got the game from ProcJam)

**Comment by fstltna** [comment]
Hi, thanks for trying it out. I have it hard coded right now, i will work on updating the autoconf files to look for it in other locations.

**Comment by fstltna** [comment]
I have solved this issue by switching to native c expressions instead of the external libpcre library. Hopefully this will now compile 64bit though I can't test it...

**Comment by CyberKiller40** [comment]
Just tested - compiles ok! :-) The produced binaries appear to run also, or start at least, cause there's a lot of hardcoded paths so when I have game files in another location it doesn't really work too well.

**Comment by fstltna** [comment]
Awesome, glad to hear it. I will look into any hard coded paths. Thanks for your help!
